# Generated by Django 3.1.3 on 2023-07-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230707_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='lesson_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_question',
        ),
    ]
